import { useEffect, useState } from 'react';
import api from '../../lib/api';
import { useAuthStore } from '../../store/authStore';

interface Payslip {
  id: string;
  month: number;
  year: number;
  basicSalary: number;
  hra: number;
  allowances: number;
  grossSalary: number;
  pf: number;
  tax: number;
  otherDeductions: number;
  totalDeductions: number;
  netSalary: number;
  status: string;
  generatedAt: string;
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function PayslipsPage() {
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPayslip, setSelectedPayslip] = useState<Payslip | null>(null);
  const { user } = useAuthStore();

  useEffect(() => {
    loadPayslips();
  }, []);

  const loadPayslips = async () => {
    try {
      const employeeId = user?.employee?.id;
      if (!employeeId) return;
      const res = await api.get(`/payroll/payslips/${employeeId}`);
      setPayslips(res.data.data || []);
    } catch {
      console.error('Failed to load payslips');
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <div className="loading-page"><div className="spinner"></div><p>Loading payslips...</p></div>;

  return (
    <div>
      <div className="page-header">
        <h1>My Payslips</h1>
        <p>View and download your monthly payslips</p>
      </div>

      {payslips.length === 0 ? (
        <div className="card">
          <div className="empty-state">
            <div className="empty-state-icon">💰</div>
            <h3>No payslips found</h3>
            <p>Your payslips will appear here once they are generated by HR.</p>
          </div>
        </div>
      ) : (
        <>
          <div className="card" style={{ marginBottom: 'var(--space-5)' }}>
            <div className="card-body" style={{ overflowX: 'auto' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Period</th>
                    <th>Gross Salary</th>
                    <th>Deductions</th>
                    <th>Net Salary</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {payslips.map((p) => (
                    <tr key={p.id}>
                      <td style={{ fontWeight: 600 }}>{MONTHS[p.month - 1]} {p.year}</td>
                      <td>₹{p.grossSalary.toLocaleString('en-IN')}</td>
                      <td style={{ color: 'var(--error-600)' }}>-₹{p.totalDeductions.toLocaleString('en-IN')}</td>
                      <td style={{ fontWeight: 700, color: 'var(--success-700)' }}>₹{p.netSalary.toLocaleString('en-IN')}</td>
                      <td>
                        <span className={`badge ${p.status === 'PAID' ? 'badge-success' : p.status === 'PUBLISHED' ? 'badge-info' : 'badge-neutral'}`}>
                          {p.status}
                        </span>
                      </td>
                      <td>
                        <button className="btn btn-sm btn-secondary" onClick={() => setSelectedPayslip(p)}>
                          View Details
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Payslip Detail Modal */}
          {selectedPayslip && (
            <div className="modal-overlay" onClick={() => setSelectedPayslip(null)}>
              <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 520 }}>
                <div className="modal-header">
                  <div className="modal-title">Payslip — {MONTHS[selectedPayslip.month - 1]} {selectedPayslip.year}</div>
                  <button className="modal-close" onClick={() => setSelectedPayslip(null)}>✕</button>
                </div>
                <div className="modal-body">
                  <div style={{ display: 'grid', gap: 'var(--space-3)' }}>
                    <h4 style={{ fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-secondary)', letterSpacing: '0.5px' }}>Earnings</h4>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Basic Salary</span><span>₹{selectedPayslip.basicSalary.toLocaleString('en-IN')}</span></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>HRA</span><span>₹{selectedPayslip.hra.toLocaleString('en-IN')}</span></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Allowances</span><span>₹{selectedPayslip.allowances.toLocaleString('en-IN')}</span></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 700, borderTop: '1px solid var(--border-primary)', paddingTop: 'var(--space-2)' }}><span>Gross Salary</span><span>₹{selectedPayslip.grossSalary.toLocaleString('en-IN')}</span></div>

                    <h4 style={{ fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-secondary)', letterSpacing: '0.5px', marginTop: 'var(--space-4)' }}>Deductions</h4>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>PF</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.pf.toLocaleString('en-IN')}</span></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Tax</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.tax.toLocaleString('en-IN')}</span></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Other</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.otherDeductions.toLocaleString('en-IN')}</span></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 700, borderTop: '1px solid var(--border-primary)', paddingTop: 'var(--space-2)' }}><span>Total Deductions</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.totalDeductions.toLocaleString('en-IN')}</span></div>

                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '1.1rem', fontWeight: 800, marginTop: 'var(--space-4)', background: 'var(--success-50)', padding: 'var(--space-3) var(--space-4)', borderRadius: 'var(--radius-md)' }}><span>Net Salary</span><span style={{ color: 'var(--success-700)' }}>₹{selectedPayslip.netSalary.toLocaleString('en-IN')}</span></div>
                  </div>
                </div>
                <div className="modal-footer">
                  <button className="btn btn-secondary" onClick={() => setSelectedPayslip(null)}>Close</button>
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
