import { useEffect, useState } from 'react';
import api from '../../lib/api';
import { useAuthStore } from '../../store/authStore';

interface Payslip {
  id: string;
  month: number;
  year: number;
  basicSalary: number;
  hra: number;
  allowances: number;
  grossSalary: number;
  pf: number;
  tax: number;
  otherDeductions: number;
  totalDeductions: number;
  netSalary: number;
  status: string;
  generatedAt: string;
}

interface PayslipRequest {
  id: string;
  month: number;
  year: number;
  purpose: string;
  status: string;
  remarks: string | null;
  createdAt: string;
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function PayslipsPage() {
  const [activeTab, setActiveTab] = useState<'payslips' | 'requests'>('payslips');
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [requests, setRequests] = useState<PayslipRequest[]>([]);
  const [loading, setLoading] = useState(true);
  
  const [selectedPayslip, setSelectedPayslip] = useState<Payslip | null>(null);
  
  // Request Modal State
  const [showRequestModal, setShowRequestModal] = useState(false);
  const [reqMonth, setReqMonth] = useState(new Date().getMonth() + 1);
  const [reqYear, setReqYear] = useState(new Date().getFullYear());
  const [reqPurpose, setReqPurpose] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const { user } = useAuthStore();

  useEffect(() => {
    loadData();
  }, [activeTab]);

  const loadData = async () => {
    setLoading(true);
    try {
      if (activeTab === 'payslips') {
        const employeeId = user?.employee?.id;
        if (!employeeId) return;
        const res = await api.get(`/payroll/payslips`);
        setPayslips(res.data.data || []);
      } else {
        const res = await api.get('/payroll/requests/me');
        setRequests(res.data.data || []);
      }
    } catch {
      console.error('Failed to load data');
    } finally {
      setLoading(false);
    }
  };

  const handleRequestSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      await api.post('/payroll/requests', {
        month: reqMonth,
        year: reqYear,
        purpose: reqPurpose
      });
      setShowRequestModal(false);
      setReqPurpose('');
      loadData();
    } catch (err) {
      console.error(err);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div>
      <div className="page-header-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div className="page-header" style={{ marginBottom: 0 }}>
          <h1>My Payslips</h1>
          <p>View payslips or request official stamped copies</p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowRequestModal(true)}>
          + Request Payslip
        </button>
      </div>

      <div className="tabs" style={{ marginTop: 'var(--space-4)' }}>
        <button className={`tab-btn ${activeTab === 'payslips' ? 'active' : ''}`} onClick={() => setActiveTab('payslips')}>My Payslips</button>
        <button className={`tab-btn ${activeTab === 'requests' ? 'active' : ''}`} onClick={() => setActiveTab('requests')}>My Requests</button>
      </div>

      {loading ? (
        <div className="loading-page" style={{ height: '30vh' }}><div className="spinner"></div></div>
      ) : activeTab === 'payslips' ? (
        // --- PAYSLIPS TAB ---
        payslips.length === 0 ? (
          <div className="card">
            <div className="empty-state">
              <div className="empty-state-icon">💰</div>
              <h3>No payslips found</h3>
              <p>Your payslips will appear here once generated by HR.</p>
            </div>
          </div>
        ) : (
          <div className="card">
            <div className="card-body" style={{ overflowX: 'auto' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Period</th>
                    <th>Gross Salary</th>
                    <th>Deductions</th>
                    <th>Net Salary</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {payslips.map((p) => (
                    <tr key={p.id}>
                      <td style={{ fontWeight: 600 }}>{MONTHS[p.month - 1]} {p.year}</td>
                      <td>₹{p.grossSalary.toLocaleString('en-IN')}</td>
                      <td style={{ color: 'var(--error-600)' }}>-₹{p.totalDeductions.toLocaleString('en-IN')}</td>
                      <td style={{ fontWeight: 700, color: 'var(--success-700)' }}>₹{p.netSalary.toLocaleString('en-IN')}</td>
                      <td>
                        <span className={`badge ${p.status === 'PAID' ? 'badge-success' : p.status === 'PUBLISHED' ? 'badge-info' : 'badge-neutral'}`}>
                          {p.status}
                        </span>
                      </td>
                      <td>
                        <button className="btn btn-sm btn-secondary" onClick={() => setSelectedPayslip(p)}>
                          View Details
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )
      ) : (
        // --- REQUESTS TAB ---
        requests.length === 0 ? (
          <div className="card">
            <div className="empty-state">
              <div className="empty-state-icon">📄</div>
              <h3>No requests found</h3>
              <p>You haven't made any special payslip requests yet.</p>
            </div>
          </div>
        ) : (
          <div className="card">
            <div className="card-body" style={{ overflowX: 'auto' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Requested On</th>
                    <th>For Period</th>
                    <th>Purpose</th>
                    <th>Status</th>
                    <th>HR Remarks</th>
                  </tr>
                </thead>
                <tbody>
                  {requests.map((r) => (
                    <tr key={r.id}>
                      <td>{new Date(r.createdAt).toLocaleDateString()}</td>
                      <td style={{ fontWeight: 600 }}>{MONTHS[r.month - 1]} {r.year}</td>
                      <td>{r.purpose}</td>
                      <td>
                        <span className={`badge ${r.status === 'APPROVED' ? 'badge-success' : r.status === 'REJECTED' ? 'badge-error' : 'badge-warning'}`}>
                          {r.status}
                        </span>
                      </td>
                      <td style={{ color: 'var(--text-secondary)' }}>{r.remarks || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )
      )}

      {/* Request Modal */}
      {showRequestModal && (
        <div className="modal-overlay" onClick={() => setShowRequestModal(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 400 }}>
            <div className="modal-header">
              <div className="modal-title">Request Official Payslip</div>
              <button className="modal-close" onClick={() => setShowRequestModal(false)}>✕</button>
            </div>
            <form onSubmit={handleRequestSubmit}>
              <div className="modal-body">
                <div className="form-group">
                  <label className="form-label">Month</label>
                  <select value={reqMonth} onChange={e => setReqMonth(Number(e.target.value))} required>
                    {MONTHS.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Year</label>
                  <select value={reqYear} onChange={e => setReqYear(Number(e.target.value))} required>
                    {[2024, 2025, 2026].map(y => <option key={y} value={y}>{y}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Purpose (e.g. Visa, Loan)</label>
                  <input type="text" value={reqPurpose} onChange={e => setReqPurpose(e.target.value)} required placeholder="State why you need this official document" />
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowRequestModal(false)}>Cancel</button>
                <button type="submit" className="btn btn-primary" disabled={submitting}>
                  {submitting ? 'Submitting...' : 'Submit Request'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Detail Modal */}
      {selectedPayslip && (
        <div className="modal-overlay" onClick={() => setSelectedPayslip(null)}>
          <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 520 }}>
            <div className="modal-header">
              <div className="modal-title">Payslip — {MONTHS[selectedPayslip.month - 1]} {selectedPayslip.year}</div>
              <button className="modal-close" onClick={() => setSelectedPayslip(null)}>✕</button>
            </div>
            <div className="modal-body">
              <div style={{ display: 'grid', gap: 'var(--space-3)' }}>
                <h4 style={{ fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-secondary)', letterSpacing: '0.5px' }}>Earnings</h4>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Basic Salary</span><span>₹{selectedPayslip.basicSalary.toLocaleString('en-IN')}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>HRA</span><span>₹{selectedPayslip.hra.toLocaleString('en-IN')}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Allowances</span><span>₹{selectedPayslip.allowances.toLocaleString('en-IN')}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 700, borderTop: '1px solid var(--border-primary)', paddingTop: 'var(--space-2)' }}><span>Gross Salary</span><span>₹{selectedPayslip.grossSalary.toLocaleString('en-IN')}</span></div>

                <h4 style={{ fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-secondary)', letterSpacing: '0.5px', marginTop: 'var(--space-4)' }}>Deductions</h4>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>PF</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.pf.toLocaleString('en-IN')}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Tax</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.tax.toLocaleString('en-IN')}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}><span>Other</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.otherDeductions.toLocaleString('en-IN')}</span></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 700, borderTop: '1px solid var(--border-primary)', paddingTop: 'var(--space-2)' }}><span>Total Deductions</span><span style={{ color: 'var(--error-600)' }}>-₹{selectedPayslip.totalDeductions.toLocaleString('en-IN')}</span></div>

                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '1.1rem', fontWeight: 800, marginTop: 'var(--space-4)', background: 'var(--success-50)', padding: 'var(--space-3) var(--space-4)', borderRadius: 'var(--radius-md)' }}><span>Net Salary</span><span style={{ color: 'var(--success-700)' }}>₹{selectedPayslip.netSalary.toLocaleString('en-IN')}</span></div>
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setSelectedPayslip(null)}>Close</button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
